apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
spec:
  project: default
  source:
    repoURL: https://github.com/Ty9000/nginx-test.git
    targetRevision: HEAD
    path: nginx2
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
