apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
spec:
  project: default
  source:
    repoURL: /home/ty9000/Documents/argocd
    targetRevision: HEAD
    path: nginx2
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx2

